### ISSUE TITLE
Is there any drop-down option in Dataloader?

### ISSUE THREAD

**Issue by yellowjs0304** [XinzeLee/polygon-yolov5#42]
Hi, i'm using a custom [repo ](https://github.com/XinzeLee/PolygonObjectDetection)that related with your yolov5.

I found some of my labels are dropped in training process. I wondered is there any option to control the number of loaded data? (like max_object_NUM) or Is there an option to drop some label data?

Below images are sample.
As you can see, there's some of row label is dropped.
![image](https://user-images.githubusercontent.com/30281608/223664886-c4b67f26-eee6-4bae-b4f0-3481c8c012a1.png)
![image](https://user-images.githubusercontent.com/30281608/223665022-48101906-7898-43d1-b018-f70c3ae1dcb7.png)

If anyone know about this, please help me.

**Comment by yellowjs0304** [comment]
I found the solution, There's a filtering function in [utils/datasets.py](https://github.com/XinzeLee/PolygonObjectDetection/blob/main/polygon-yolov5/utils/datasets.py#L909).

It help to delete unnecessary(or something uncorrect) augmented labels. But in my case, I wanted to use whole labeled data.

I modified as below. and, now the dropped labels are restored.
```
# BEFORE
        i = polygon_box_candidates(box1=targets[:, 1:].T * s, box2=new.T, area_thr=0.08) 
        targets = targets[i]
        targets[:, 1:] = new[i]

# Modified
        #i = polygon_box_candidates(box1=targets[:, 1:].T * s, box2=new.T, area_thr=0.08) 
        i = np.full(i.shape, True)
        targets = targets[i]
        targets[:, 1:] = new[i]
```
I don't know it maybe affected with mAP but, i have only a few, so all of data are important.
I didn't apply much of augments, I just looking forward the mAP is not that affected.

**Comment by Neo-YH** [comment]
UnboundLocalError: local variable 'i' referenced before assignment
May I remove the polygon_box_candidates directly?
