### ISSUE TITLE
Why is the calculation of P, R, mAP so slow?

### ISSUE THREAD

**Issue by lemon1022** [XinzeLee/polygon-yolov5#43]
I found that the reason for the slowness is a function added by the author, which uses a while loop, and the number of loops is very large. Is there any optimization?

**Comment by syz825211943** [comment]
Have you solved this problem? I meet this problem and don't know how solve it. Do you have some advice? thx! @lemon1022

**Comment by lemon1022** [comment]
@syz825211943 In the early stage of training, the features obtained by the model are not obvious, so the calculation is slow. By printing the log, it is found that in the first few rounds, the amount of while loop in nms is large. In the middle and late stages of training, the speed slowly becomes faster. Another solution is to increase the amount of data so that the model can get features faster.
